### ISSUE TITLE
Jugador ganador: debes incrementar partidas ganadas

### ISSUE THREAD

**Issue by lmagarin** [pabloleonalcaide/juegoDeCartas#14]
https://github.com/pabloleonalcaide/juegoDeCartas/blob/master/sieteYmedia/Partida.java#L34
Además, ¿para qué creas el objeto?
https://github.com/pabloleonalcaide/juegoDeCartas/blob/master/sieteYmedia/Partida.java#L26

**Comment by pabloleonalcaide** [comment]
Corregido
