### ISSUE TITLE
Ranking... ¿ordenado?

### ISSUE THREAD

**Issue by lmagarin** [pabloleonalcaide/juegoDeCartas#2]
https://github.com/pabloleonalcaide/juegoDeCartas/blob/correcciones/sieteYmedia/Ranking.java#L18
Entiendo que no lo ordenas...
Utiliza Collection.sort()

**Comment by pabloleonalcaide** [comment]
De acuerdo, usé esta forma porque no me funcionaba el sort, pero creo que ya entiendo la manera de hacerlo, lo modifico.

**Comment by pabloleonalcaide** [comment]
Resuelto!
