### ISSUE TITLE
Delegación

### ISSUE THREAD

**Issue by lmagarin** [pabloleonalcaide/juegoDeCartas#5]
https://github.com/pabloleonalcaide/juegoDeCartas/blob/correcciones/sieteYmedia/Partida.java#L111
Es una técnica que delega en otro objeto, normalmente tiene como relación la composición, en este caso
carta debería delegar en su figura
	double valor = carta.getValor();

**Comment by pabloleonalcaide** [comment]
Corregido, es un detalle que suelo pasar por alto, así que me lo apunto en grande.
