### ISSUE TITLE
puntuacion... ¿de jugador o de partida?

### ISSUE THREAD

**Issue by lmagarin** [pabloleonalcaide/juegoDeCartas#7]
https://github.com/pabloleonalcaide/juegoDeCartas/blob/correcciones/sieteYmedia/Jugador.java#L5
La puntuación debería ser definida dentro de partida... porque es intrínseca a una partida. 
Un vector de puntuaciones de los participantes... como variable local o como campo, inicialmente todos a cero

**Comment by pabloleonalcaide** [comment]
Se que esto se comentó en clase, pero no termino de comprenderlo, me cuesta ver la puntuación como algo aislado del jugador, pero trabajaré en esto. Gracias

**Comment by lmagarin** [comment]
Efectivamente la puntuación es de un jugador, pero cuando la partida finaliza... no tiene sentido mantenerla... Sólo tiene sentido dentro de la partida.
Además, tu problema es que no has creado la clase Jugadores... envoltorio de un ArrayList de Jugador

**Comment by pabloleonalcaide** [comment]
Corregido, este ha costado verlo
